/*
 * SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include "multimodalRunner.h"
#include <array>
#include <common/tensor.h>
#include <cuda_fp16.h>
#include <vector>

namespace trt_edgellm
{
namespace rt
{

//! \brief Configuration for Nemotron-Omni RADIO vision encoder
struct NemotronOmniViTConfig
{
    int64_t maxNumBlocks{0};    //!< Maximum number of image tiles (across the batch)
    int64_t minNumBlocks{0};    //!< Minimum number of image tiles (across the batch)
    int64_t numChannels{3};     //!< Number of image channels (RGB)
    int64_t outHiddenSize{0};   //!< Output hidden dimension (LLM hidden size)
    int64_t blockImageSizeH{0}; //!< Image height per tile (preferred_resolution)
    int64_t blockImageSizeW{0}; //!< Image width per tile (preferred_resolution)

    int64_t tokensPerBlock{256}; //!< Tokens per tile after pixel shuffle

    int32_t vocabSize{0};          //!< Vocabulary size (image token ID offset)
    int32_t imgContextTokenId{18}; //!< Image context token ID
    int32_t imgStartTokenId{0};    //!< Image start token ID
    int32_t imgEndTokenId{0};      //!< Image end token ID

    std::array<float, 3> imageMean{{0.5F, 0.5F, 0.5F}}; //!< Image normalization mean
    std::array<float, 3> imageStd{{0.5F, 0.5F, 0.5F}};  //!< Image normalization std

    int64_t minImageTokensPerImage{0}; //!< Minimum image tokens generated by each image. Used for resizing.
    int64_t maxImageTokensPerImage{0}; //!< Maximum image tokens generated by each image. Used for resizing.
};

//! \brief Runner for Nemotron-Omni RADIO vision encoder
//!
//! Handles preprocessing and inference for the RADIO ViT encoder used in
//! Nemotron-Omni multimodal models. Images are tiled to an aspect-ratio-matched
//! grid within the per-image tile budget, with a thumbnail appended when the
//! grid produces more than one tile.
class NemotronOmniViTRunner : public MultimodalRunner
{
public:
    //! \brief Constructor for NemotronOmniViTRunner
    //! \param[in] engineDir Directory containing the TensorRT engine files
    //! \param[in] stream CUDA stream for execution
    //! \throws std::runtime_error if engineDir does not contain valid engine files
    //! \throws std::runtime_error if buffer allocation fails
    //! \throws std::runtime_error if a CUDA error occurs
    NemotronOmniViTRunner(std::string const& engineDir, cudaStream_t stream);

    ~NemotronOmniViTRunner() noexcept = default;

    //! \brief Preprocess multimodal input including images and text
    //! \param[in] request LLM generation request containing images and text
    //! \param[in,out] batchedInputIds Batched input token IDs after preprocessing
    //! \param[in] tokenizer Tokenizer for text processing
    //! \param[in,out] mropeCosSinOut MRoPE cos/sin output tensor (unused by this model)
    //! \param[in] stream CUDA stream for execution
    //! \return True if preprocessing succeeded, false otherwise
    bool preprocess(rt::LLMGenerationRequest const& request, std::vector<std::vector<int32_t>>& batchedInputIds,
        tokenizer::Tokenizer const* tokenizer, [[maybe_unused]] rt::OptionalOutputTensor mropeCosSinOut,
        cudaStream_t stream, bool imageOnly = false) noexcept override;

    //! \brief Run inference on the vision encoder
    //! \param[in] stream CUDA stream for execution
    //! \return True if inference succeeded, false otherwise
    bool infer(cudaStream_t stream) noexcept override;

    //! \brief Validate and load configuration from JSON file
    //! \param[in] engineDir Path to engine directory
    //! \return True if configuration is valid and loaded successfully, false otherwise
    bool validateAndFillConfig(std::string const& engineDir) override;

    //! \brief Allocate buffers for inference
    //! \param[in] stream CUDA stream for execution
    //! \return True if allocation succeeded, false otherwise
    //! \throws std::runtime_error if a CUDA error occurs
    bool allocateBuffer(cudaStream_t stream) override;

private:
    //! \brief Preprocess all images in the request using dynamic tiling and thumbnail
    //! \param[in] request LLM generation request containing images
    //! \param[out] imageTokenLengths Token lengths for each image
    //! \param[out] numImages Number of images per request
    //! \param[in] stream CUDA stream for execution
    //! \throws std::runtime_error if image size is unexpected, or number of blocks is excessive
    void imagePreprocess(rt::LLMGenerationRequest const& request, std::vector<int64_t>& imageTokenLengths,
        std::vector<int64_t>& numImages, cudaStream_t stream);

    //! \brief Format and process a single image patch
    //! \param[in] image Input image data
    //! \param[out] imageTokenLengths Token lengths for each image
    //! \param[out] numImages Number of images processed
    //! \param[out] totalNumBlocks Total number of image blocks
    //! \param[in] isThumbnail Whether the image is a thumbnail
    //! \param[in] stream CUDA stream for execution
    //! \throws std::runtime_error if image size is unexpected, or number of blocks is excessive
    void formatPatch(rt::imageUtils::ImageData const& image, std::vector<int64_t>& imageTokenLengths,
        int64_t& numImages, int64_t& totalNumBlocks, bool isThumbnail, cudaStream_t stream);

    //! \brief Preprocess text portion of the request
    //! \param[in] request LLM generation request
    //! \param[in,out] batchInputIds Batch of input token IDs
    //! \param[in] numImages Number of images per request
    //! \param[in] imageTokenLengths Token lengths for each image
    //! \param[in] tokenizer Tokenizer for text processing
    void textPreprocess(rt::LLMGenerationRequest const& request, std::vector<std::vector<int32_t>>& batchInputIds,
        std::vector<int64_t> const& numImages, std::vector<int64_t> const& imageTokenLengths,
        trt_edgellm::tokenizer::Tokenizer const* tokenizer);

    NemotronOmniViTConfig mConfig;                   //!< Nemotron-Omni RADIO ViT configuration
    rt::Tensor mVitInput{};                          //!< Vision encoder input tensor
    rt::Tensor mImageMean{};                         //!< Image mean tensor
    rt::Tensor mImageStd{};                          //!< Image standard deviation tensor
    rt::Tensor mImageDevice{};                       //!< Temporary image buffer for preprocessing
    rt::Tensor mNormalizedImageDevice{};             //!< Temporary normalized image buffer
    rt::imageUtils::ImageData mResizedImageHost{};   //!< Pre-allocated buffer for image resizing
    rt::imageUtils::ImageData mThumbnailImageHost{}; //!< Pre-allocated buffer for thumbnail resize
    int64_t mTotalNumBlocks{0};                      //!< Total blocks preprocessed (for batched infer)
};

} // namespace rt
} // namespace trt_edgellm
