/*
 * SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include "multimodalRunner.h"
#include <cuda_fp16.h>
#include <nlohmann/json.hpp>
#include <vector>

namespace trt_edgellm
{
namespace rt
{

//! \brief What the LLM token stream & MRoPE see for one vision span (HF `get_rope_index` `llm_grid_*` view).
struct LlmVisionBlock
{
    int64_t numTokens{0};     //!< LLM tokens this span inserts (llmGridT * llmGridH * llmGridW)
    int64_t llmGridT{0};      //!< HF llm_grid_t (== vit.gridT)
    int64_t llmGridH{0};      //!< HF llm_grid_h (vit.gridH / mergeSize)
    int64_t llmGridW{0};      //!< HF llm_grid_w (vit.gridW / mergeSize)
    int64_t secondPerGrid{1}; //!< HF second_per_grid_t = int(temporalPatchSize / fps)
};

//! \brief What the ViT engine sees for one vision span (HF `grid_thw`; cu_seqlens / rotary / fast-pos-emb / window).
struct VitFrameGrid
{
    int64_t gridT{0};      //!< HF grid_t — frames (each emits one per-frame gridH*gridW cu_seqlens block)
    int64_t gridH{0};      //!< HF grid_h — patch-grid height (resizedHeight / patchSize)
    int64_t gridW{0};      //!< HF grid_w — patch-grid width  (resizedWidth  / patchSize)
    int64_t patchStart{0}; //!< Absolute ViT patch offset where this span begins (rotary / fast-pos base)

    //! \brief Value equality: this is exactly the ViT-input cache key (cu_seqlens / rotary / extra inputs).
    bool operator==(VitFrameGrid const& o) const
    {
        return gridT == o.gridT && gridH == o.gridH && gridW == o.gridW && patchStart == o.patchStart;
    }
};

//! \brief A VisionSpan is one block of vision tokens — an image, or one video frame-group from a single
//!        <|vision_start|> — held in both views: the LLM/MRoPE token view (llm) and the ViT patch view (vit).
struct VisionSpan
{
    LlmVisionBlock llm{};
    VitFrameGrid vit{};
};

//! \brief Configuration for Qwen-VL vision encoder
struct QwenViTConfig
{
    int64_t maxHW{0};         //!< Maximum height * width
    int64_t minHW{0};         //!< Minimum height * width
    int64_t inputDim{0};      //!< Input dimension
    int64_t vitPosEmbDim{0};  //!< Vision transformer position embedding dimension
    int64_t outHiddenSize{0}; //!< Output hidden dimension size

    int32_t vocabSize{0};              //!< Vocabulary size
    int32_t visionStartTokenId{0};     //!< Token ID for vision start
    int32_t visionEndTokenId{0};       //!< Token ID for vision end
    int32_t imageTokenId{0};           //!< Token ID for image placeholder
    int32_t videoTokenId{0};           //!< Token ID for video placeholder
    float mropeTheta{0};               //!< Multi-dimensional RoPE theta parameter
    int64_t patchSize{0};              //!< Patch size in pixels
    int64_t temporalPatchSize{0};      //!< Temporal patch size for video
    int64_t mergeSize{0};              //!< Merge size for patches
    int32_t mropeSectionH{0};          //!< MRoPE section: number of frequency pairs for height
    int32_t mropeSectionW{0};          //!< MRoPE section: number of frequency pairs for width
    bool mropeInterleaved{false};      //!< Whether MRoPE uses interleaved layout (from config)
    int64_t minImageTokensPerImage{0}; //!< Minimum image tokens generated by each image. Used for resizing.
    int64_t maxImageTokensPerImage{0}; //!< Maximum image tokens generated by each image. Used for resizing.
    int64_t maxNumImages{0};           //!< Maximum number of images per request. Used for pre-allocation.

    std::vector<float> imageMean{}; //!< Image normalization mean values (RGB)
    std::vector<float> imageStd{};  //!< Image normalization standard deviation values (RGB)
};

//! \brief Runner for Qwen-VL vision encoder
//!
//! This class handles the preprocessing and inference of Qwen-VL vision encoder,
class QwenViTRunner : public MultimodalRunner
{
public:
    //! \brief Constructor for QwenViTRunner
    //! \param[in] engineDir Directory containing the TensorRT engine files
    //! \param[in] llmMaxBatchSize Maximum batch size from LLM engine
    //! \param[in] llmMaxSequenceLength Maximum sequence length from LLM engine
    //! \param[in] stream CUDA stream for execution
    //! \throws std::runtime_error if engine directory does not contain engine files, or if buffer allocation fails
    //! \throws json::type_error if JSON configuration contains unexpected datatypes
    QwenViTRunner(
        std::string const& engineDir, int32_t llmMaxBatchSize, int32_t llmMaxSequenceLength, cudaStream_t stream);

    ~QwenViTRunner() noexcept = default;

    //! \brief Load config + allocate buffers. Called by the factory AFTER construction (not from the constructor) so
    //!        the per-model virtual hooks dispatch to the subclass. \throws std::runtime_error on failure.
    void initialize(cudaStream_t stream);

    //! \brief Preprocess multimodal input including images and text
    //! \param[in] request LLM generation request containing images and text
    //! \param[in,out] batchedInputIds Batched input token IDs after preprocessing
    //! \param[in] tokenizer Tokenizer for text processing
    //! \param[out] mropeCosSinOut MRope cos/sin output cache (required when !imageOnly)
    //! \param[in] stream CUDA stream for execution
    //! \return True if preprocessing succeeded, false otherwise
    //! \throws std::runtime_error if sequence length is invalid, or a CUDA error occurs
    bool preprocess(rt::LLMGenerationRequest const& request, std::vector<std::vector<int32_t>>& batchedInputIds,
        tokenizer::Tokenizer const* tokenizer, rt::OptionalOutputTensor mropeCosSinOut, cudaStream_t stream,
        bool imageOnly = false) override;

    //! \brief Encode the system prompt and generate ND-RoPE parameters for the system prompt for KVCache saving.
    //! \param[in] systemPrompt System prompt string
    //! \param[in] tokenizer Tokenizer for text processing
    //! \param[out] mropeCosSinOut MRope cos/sin output cache (required for non-empty system prompts)
    //! \param[in] stream CUDA stream for execution
    //! \return True if preprocessing succeeded, false otherwise
    bool preprocessSystemPrompt(std::string const& systemPrompt, tokenizer::Tokenizer const* tokenizer,
        rt::OptionalOutputTensor mropeCosSinOut, cudaStream_t stream) override;

    //! \brief Run inference on the vision encoder
    //! \param[in] stream CUDA stream for execution
    //! \return True if inference succeeded, false otherwise
    bool infer(cudaStream_t stream) noexcept override;

    //! \brief Validate and load configuration from JSON file
    //! \param[in] engineDir Path to engine directory
    //! \return True if configuration is valid and loaded successfully, false otherwise
    //! \throws json::type_error if JSON configuration contains unexpected datatypes
    bool validateAndFillConfig(std::string const& engineDir) override;

    //! \brief Allocate buffers for inference
    //! \return True if allocation succeeded, false otherwise
    //! \throws std::runtime_error if a CUDA operation fails
    bool allocateBuffer(cudaStream_t stream) override;

    //! \brief Get deepstack features for Qwen3-VL
    //! \return Optional input tensors vector containing deepstack features
    rt::OptionalInputTensors getDeepstackFeatures() override;

    //! \brief Get MRoPE rope deltas for each batch from the last preprocess/infer run.
    //! \return Vector of length (batch size): delta = maxMropePositionId + 1 - inputIdSize per batch; empty if not yet
    //! set.
    std::vector<int64_t> const& getMropeRopeDeltasPerBatch() const noexcept
    {
        return mMropeRopeDeltasPerBatch;
    }

protected:
    //! \name Per-model strategy hooks. Base implementations = Qwen2-VL (the simplest model: image-only, 2D resize,
    //!       rotary+cu_seqlens only, incrementing pad, spatial-only MRoPE advance). Subclasses override what they add.
    //! @{

    //! \brief Read model-specific config fields into mConfig.
    //! \return false on missing required fields.
    virtual bool validateExtraConfig(nlohmann::json const& jsonConfig);

    //! \brief Allocate model-specific I/O buffers beyond the shared ones.
    //! \return false on failure.
    virtual bool allocateExtraBuffers(int64_t maxImageTokens);

    //! \brief Build the model-specific input tensors.
    virtual void buildExtraInputs(
        std::vector<VisionSpan> const& spans, int64_t totalSeqLength, int64_t totalImageTokens, cudaStream_t stream);

    //! \brief Bind the model-specific input shapes before enqueue.
    //! \return false on failure.
    virtual bool bindExtraInputShapes();

    //! \brief Append this image buffer's vision spans. \see VisionSpan.
    //! \return {totalSeqLen, totalGridT} of the appended spans (Σ gridT*gridH*gridW, Σ gridT) for formatPatch.
    virtual std::tuple<int64_t, int64_t> computeVisionSpans(
        rt::imageUtils::ImageData const& image, int64_t patchBase, std::vector<VisionSpan>& spans);

    //! \brief Fill MRoPE position ids — one standalone implementation per model, mirroring each HF get_rope_index.
    virtual void getMRopePositionIds(
        std::vector<std::vector<int32_t>> const& batchInputIds, std::vector<VisionSpan> const& spans) noexcept;

    //! \brief Calculate resized image dimensions based on dynamic resolution constraints
    //! \param[in] numFrames Source frame count (1 for still image, >1 for video; used only by the 3D override)
    //! \param[in] height Input image height
    //! \param[in] width Input image width
    //! \param[in] maxRatio Maximum aspect ratio (default: 200)
    //! \return Tuple of (resized_height, resized_width)
    //! \throws std::runtime_error if aspect ratio is invalid
    virtual std::tuple<int64_t, int64_t> getResizedImageSize(
        int64_t numFrames, int64_t height, int64_t width, int64_t maxRatio = 200);

    //! \brief Preprocess text: expand each vision pad using the spans (in order).
    //! \param[in] request LLM generation request
    //! \param[out] batchInputIds Batch of input token IDs
    //! \param[in] spans Vision spans (flattened, global order) \param[in] tokenizer Tokenizer
    virtual void textPreprocess(rt::LLMGenerationRequest const& request,
        std::vector<std::vector<int32_t>>& batchInputIds, std::vector<VisionSpan> const& spans,
        trt_edgellm::tokenizer::Tokenizer const* tokenizer);
    //! @}

    //! \brief Format and process a single image buffer (or video frame stack): append its spans and
    //!        copy/normalize/transpose its (padded) frames into the ViT input scratch.
    //! \param[in] image Input media data (image with frames==1 or video with frames>1)
    //! \param[in,out] spans Flat global-order span list to append this buffer's spans to
    //! \param[in,out] patchBase Running ViT patch offset; read as this buffer's base, advanced by its patch count
    //! \param[in] stream CUDA stream for execution
    //! \throws std::runtime_error if image dimensions are incompatible with patch size, or sequence length is out of
    //! range, or the padded frame stack overflows the device scratch buffer
    //! \throws std::runtime_error if a CUDA error occurs
    void formatPatch(rt::imageUtils::ImageData const& image, std::vector<VisionSpan>& spans, int64_t& patchBase,
        cudaStream_t stream);

    //! \brief Build per-frame cumulative sequence lengths + max per-frame seq len for the whole batch.
    //! \param[in] spans Finished flat global-order span list
    //! \param[out] cuSeqlensData Host cu_seqlens buffer
    //! \param[out] cuSeqlensSize Number of cu_seqlens entries written
    //! \param[out] maxSeqLen Max per-frame seq length
    void buildCuSeqlens(
        std::vector<VisionSpan> const& spans, int32_t* cuSeqlensData, int64_t& cuSeqlensSize, int64_t& maxSeqLen) const;

    //! \brief Generate multi-dimensional RoPE parameters
    //! \param[in] batchInputIds Batch of input token IDs
    //! \param[in] spans Vision spans (flattened, global order)
    //! \param[in,out] ropeRotaryCosSinDevice RoPE rotary position encoding cache
    //! \param[in] stream CUDA stream for execution
    //! \throws std::runtime_error if shape validation fails, or a CUDA operation fails
    void generateMropeParams(std::vector<std::vector<int32_t>> const& batchInputIds,
        std::vector<VisionSpan> const& spans, rt::Tensor& ropeRotaryCosSinDevice, cudaStream_t stream);

    //! \brief Preprocess all images in the request (populates spans + ViT-side tensors)
    //! \param[in] request LLM generation request containing images
    //! \param[out] spans Vision spans (flattened, global order)
    //! \param[in] doResize Whether to resize images
    //! \param[in] stream CUDA stream for execution
    //! \throws std::runtime_error if aspect ratio is invalid
    //! \throws std::runtime_error if image dimensions are incompatible with patch size, or sequence length is out of
    //! range
    //! \throws std::runtime_error if a CUDA error occurs
    void imagePreprocess(
        rt::LLMGenerationRequest const& request, std::vector<VisionSpan>& spans, bool doResize, cudaStream_t stream);

    QwenViTConfig mConfig{};             //!< Qwen-VL configuration
    rt::Tensor mVitInput{};              //!< Vision encoder input tensor
    rt::Tensor mRotaryPosEmb{};          //!< Rotary position embeddings tensor (multi-dimensional RoPE)
    rt::Tensor mCuSeqlens{};             //!< Cumulative sequence lengths tensor
    rt::Tensor mCuSeqlensHost{};         //!< Cumulative sequence lengths host tensor
    rt::Tensor mKvLengths{};             //!< KV lengths for TRT-native attention (separate copy of cu_seqlens)
    rt::Tensor mKvLengthsWindow{};       //!< KV lengths for Qwen2.5-VL window attention (TRT-native)
    rt::Tensor mMaxSeqLenCarrier{};      //!< Shape-only input carrying max sequence length for FMHA launch
    rt::Tensor mImageMean{};             //!< Image mean tensor
    rt::Tensor mImageStd{};              //!< Image standard deviation tensor
    rt::Tensor mImageDevice{};           //!< Temporary image buffer for preprocessing
    rt::Tensor mNormalizedImageDevice{}; //!< Temporary normalized image buffer for preprocessing
    rt::imageUtils::ImageData mResizedImageHost{}; //!< Pre-allocated buffer for image resizing
    rt::Tensor mMropePositionIdsHost{};            //!< MRoPE position IDs host tensor
    rt::Tensor mMropePositionIdsDevice{};          //!< MRoPE position IDs device tensor
    // Model-specific ViT-input tensors live in the per-model subclasses.

    std::string mEngineDir;           //!< Visual engine dir (kept for the deferred initialize() config load)
    int32_t mLLMMaxBatchSize{0};      //!< Maximum batch size from LLM engine
    int32_t mLLMMaxSequenceLength{0}; //!< Maximum sequence length from LLM engine

    bool mUseTrtNativeVitAttn{false}; //!< Use TRT IAttentionV2 (from config); requires kv_lengths binding in engine
    bool mHasKvLengthsWindow{false};  //!< Whether the visual engine has kv_lengths_window binding
    bool mHasMaxSeqLenCarrier{false}; //!< Whether the visual engine has the max_seqlen_carrier binding

    std::vector<VisionSpan> mLastSpans; //!< Last round's spans; ViT-input tensors are reused when vit geometry matches.
    std::vector<int64_t> mMropeRopeDeltasPerBatch{}; //!< Used by downstream runners like Alpamayo1ActionRunner to set
                                                     //!< base MRoPE positions so the action expert's RoPE continues
                                                     //!< coherently after the VLM sequence.
};

} // namespace rt
} // namespace trt_edgellm
