# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Module definitions for the decoder stack (attention-only).

Forward-pass conventions
------------------------
``CausalLM.forward``:

    inputs_embeds        [batch, seq_len, hidden_size]            float16/bfloat16
    past_key_values      tuple of [batch, 2, num_kv_heads, past_len, head_dim] per attn-layer
    rope_rotary_cos_sin  [batch, max_pos, rotary_dim]  float32
    context_lengths      [batch]                        int32
    kvcache_start_index  [batch]                        int32
    ──────────────────────────────────────────────────────────────────────
    -> logits             [batch, seq_len, vocab_size]              float32
    -> present_key_values tuple of [batch, 2, num_kv_heads, past_len+seq_len, head_dim] per attn-layer

Checkpoint key correspondence
------------------------------
Attention layer  -> model.layers.N.self_attn.*
MLP              -> model.layers.N.mlp.*
LayerNorm        -> model.layers.N.input_layernorm.*, post_attention_layernorm.*
"""

import itertools
from dataclasses import dataclass
from typing import List, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F

from ...config import ModelConfig
from ..linear import FP16Linear, make_linear
from ..ops import attention_plugin

__all__ = [
    "OnnxSpec",
    "RMSNorm",
    "Attention",
    "MLP",
    "DecoderLayer",
    "Transformer",
    "CausalLM",
]

# ---------------------------------------------------------------------------
# ONNX export spec
# ---------------------------------------------------------------------------

_BATCH_SIZE = 1
_SEQ_LEN = 1
_PAST_LEN = 1
_MAX_POS = 4096


@dataclass
class OnnxSpec:
    """All model-specific parameters needed to call ``torch.onnx.export``.

    Produced by :meth:`CausalLM.onnx_export_spec`; consumed by
    :func:`~tensorrt_edgellm.onnx.export._export_model`.
    """
    wrapped: nn.Module
    args: tuple
    input_names: List[str]
    output_names: List[str]
    dynamic_shapes: list


def _make_flat_wrapper(model: nn.Module,
                       Na: int,
                       Nd: int,
                       eagle_base: bool = False,
                       emit_hidden_states: bool = False) -> nn.Module:
    """Build a wrapper with an explicit flat forward signature (no ``*args``).

    Using ``*flat_args`` in ``forward`` triggers a PyTorch 2.10 bug where the
    guard code generated by the non-strict exporter accesses the variadic tuple
    by index during decomposition, causing an ``IndexError``.  An explicit,
    named parameter list avoids this entirely.

    ``Na`` = number of attention layers, ``Nd`` = number of deepstack visual
    embed inputs.  This wrapper is for pure-attention (transformer-only) models.
    For hybrid Mamba models see ``_make_flat_wrapper_mamba`` in
    ``modeling_nemotron_h.py``.

    When ``eagle_base=True``, the wrapper adds ``attention_mask`` and
    ``attention_pos_id`` inputs and an extra ``hidden_states`` output for
    EAGLE3 speculative decoding.

    When ``emit_hidden_states=True`` (and ``eagle_base=False``), the wrapper
    adds only the extra ``hidden_states`` output (no extra inputs) — used by
    Qwen3-Omni where the Talker pipeline consumes the thinker's full-sequence
    last-layer normed hidden states.
    """
    has_hidden_output = eagle_base or emit_hidden_states

    param_names: List[str] = (["inputs_embeds"] +
                              [f"past_key_values_{i}" for i in range(Na)] + [
                                  "rope_rotary_cos_sin", "context_lengths",
                                  "kvcache_start_index", "last_token_ids"
                              ] + [f"deepstack_embeds_{i}" for i in range(Nd)])
    if eagle_base:
        param_names += ["attention_pos_id", "attention_mask"]

    past_kv_tuple = "({},)".format(", ".join(
        f"past_key_values_{i}" for i in range(Na))) if Na else "()"
    ds_tuple = "({},)".format(", ".join(f"deepstack_embeds_{i}"
                                        for i in range(Nd))) if Nd else "()"
    ds_kwarg = f", deepstack_embeds={ds_tuple}" if Nd > 0 else ""
    eagle_kwargs = (", attention_mask=attention_mask"
                    ", attention_pos_id=attention_pos_id"
                    if eagle_base else "")

    if has_hidden_output:
        body = (
            f"    logits, hidden_states, present_key_values = self._model(\n"
            f"        inputs_embeds, {past_kv_tuple}, rope_rotary_cos_sin, "
            f"context_lengths, kvcache_start_index, last_token_ids"
            f"{ds_kwarg}{eagle_kwargs})\n"
            f"    return (logits, hidden_states) + tuple(present_key_values)\n"
        )
    else:
        body = (
            f"    logits, present_key_values = self._model(\n"
            f"        inputs_embeds, {past_kv_tuple}, rope_rotary_cos_sin, "
            f"context_lengths, kvcache_start_index, last_token_ids"
            f"{ds_kwarg})\n"
            f"    return (logits,) + tuple(present_key_values)\n")

    src = "def _forward(self, {}):\n{}".format(", ".join(param_names), body)
    globs: dict = {}
    exec(src, globs)  # noqa: S102

    class _Wrapper(nn.Module):

        def __init__(self, m: nn.Module) -> None:
            super().__init__()
            self._model = m

    _Wrapper.forward = globs["_forward"]
    return _Wrapper(model)


# ---------------------------------------------------------------------------
# RMSNorm
# ---------------------------------------------------------------------------


class RMSNorm(nn.Module):
    """Root-mean-square layer normalisation.

    Buffer: ``weight`` [hidden_size].
    """

    def __init__(self, hidden_size: int, eps: float = 1e-6) -> None:
        super().__init__()
        self.variance_epsilon = eps
        self.weight = nn.Parameter(torch.ones(hidden_size,
                                              dtype=torch.float16))

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance +
                                                    self.variance_epsilon)
        hidden_states = hidden_states.to(input_dtype)
        return self.weight.to(input_dtype) * hidden_states


# ---------------------------------------------------------------------------
# Attention
# ---------------------------------------------------------------------------


class Attention(nn.Module):
    """Multi-head GQA attention (custom attention ONNX op).

    Submodule names match checkpoint keys:
        q_proj, k_proj, v_proj, o_proj
        q_norm, k_norm  (present only when config.has_qk_norm)
    """

    def __init__(self,
                 config: ModelConfig,
                 layer_idx: int,
                 in_features: int = 0) -> None:
        super().__init__()
        num_attention_heads = config.num_attention_heads
        num_key_value_heads = config.num_key_value_heads
        head_dim = config.head_dim
        hidden_size = config.hidden_size
        # in_features overrides the QKV projection input dimension.
        # When 0 (default), QKV projections use hidden_size as input.
        qkv_in_features = in_features or hidden_size

        self.layer_idx = layer_idx
        self.num_heads = num_attention_heads
        self.num_kv_heads = num_key_value_heads
        self.head_dim = head_dim
        self.enable_fp8_kv_cache = config.quant.kv_cache_quant == "fp8"
        self.sliding_window_size = config.sliding_window_size  # -1 means no sliding window
        module_prefix = f"layers.{layer_idx}.self_attn"

        self.q_proj = make_linear(config,
                                  qkv_in_features,
                                  num_attention_heads * head_dim,
                                  bias=config.attention_bias,
                                  module_name=f"{module_prefix}.q_proj")
        self.k_proj = make_linear(config,
                                  qkv_in_features,
                                  num_key_value_heads * head_dim,
                                  bias=config.attention_bias,
                                  module_name=f"{module_prefix}.k_proj")
        self.v_proj = make_linear(config,
                                  qkv_in_features,
                                  num_key_value_heads * head_dim,
                                  bias=config.attention_bias,
                                  module_name=f"{module_prefix}.v_proj")
        # FP8 KV-cache scales live on the proj modules (checkpoint keys
        # ``...k_proj.k_scale`` / ``...v_proj.v_scale``); they are not part of
        # FP8Linear's per-tensor weight/input scales.
        if self.enable_fp8_kv_cache:
            self.k_proj.register_buffer("k_scale", torch.ones(1))
            self.v_proj.register_buffer("v_scale", torch.ones(1))

        self.o_proj = make_linear(config,
                                  num_attention_heads * head_dim,
                                  hidden_size,
                                  module_name=f"{module_prefix}.o_proj")

        if config.has_qk_norm:
            self.q_norm = RMSNorm(head_dim, eps=config.rms_norm_eps)
            self.k_norm = RMSNorm(head_dim, eps=config.rms_norm_eps)
        else:
            self.q_norm = None
            self.k_norm = None

    def forward(
        self,
        hidden_states: torch.Tensor,
        past_key_value: torch.Tensor,
        rope_rotary_cos_sin: torch.Tensor,
        context_lengths: torch.Tensor,
        kvcache_start_index: torch.Tensor,
        attention_mask: "torch.Tensor | None" = None,
        attention_pos_id: "torch.Tensor | None" = None,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        batch_size, seq_len, _ = hidden_states.shape

        query_states = self.q_proj(hidden_states)
        key_states = self.k_proj(hidden_states)
        value_states = self.v_proj(hidden_states)

        if self.q_norm is not None:
            query_states = self.q_norm(
                query_states.reshape(batch_size, seq_len, self.num_heads,
                                     self.head_dim)).reshape(
                                         batch_size, seq_len,
                                         self.num_heads * self.head_dim)
        if self.k_norm is not None:
            key_states = self.k_norm(
                key_states.reshape(batch_size, seq_len, self.num_kv_heads,
                                   self.head_dim)).reshape(
                                       batch_size, seq_len,
                                       self.num_kv_heads * self.head_dim)

        enable_tree = attention_mask is not None and attention_pos_id is not None
        kwargs: dict = {
            "num_q_heads": self.num_heads,
            "num_kv_heads": self.num_kv_heads,
            "head_size": self.head_dim,
            "sliding_window_size": self.sliding_window_size,
            "enable_tree_attention": enable_tree,
            "enable_fp8_kv_cache": self.enable_fp8_kv_cache,
        }
        if enable_tree:
            kwargs["attention_mask"] = attention_mask
            kwargs["attention_pos_id"] = attention_pos_id
        # Always pass qkv_scales so torch.export includes a valid FLOATS
        # value in the FX graph for the unified ONNX translation.
        kwargs["qkv_scales"] = getattr(self, "_qkv_scales_float",
                                       [1.0, 1.0, 1.0])

        attn_output, present_key_value = attention_plugin(
            query_states,
            key_states,
            value_states,
            past_key_value,
            context_lengths,
            rope_rotary_cos_sin,
            kvcache_start_index,
            **kwargs,
        )
        # AttentionPlugin returns [batch, seq_len, num_heads, head_dim]; reshape for o_proj.
        attn_output = attn_output.reshape(batch_size, seq_len,
                                          self.num_heads * self.head_dim)

        return self.o_proj(attn_output), present_key_value


# ---------------------------------------------------------------------------
# MLP
# ---------------------------------------------------------------------------


class MLP(nn.Module):
    """SwiGLU MLP: gate_proj, up_proj, down_proj."""

    def __init__(self, config: ModelConfig, layer_idx: int = -1) -> None:
        super().__init__()
        module_prefix = f"layers.{layer_idx}.mlp" if layer_idx >= 0 else ""
        self.gate_proj = make_linear(
            config,
            config.hidden_size,
            config.intermediate_size,
            module_name=f"{module_prefix}.gate_proj" if module_prefix else "")
        self.up_proj = make_linear(
            config,
            config.hidden_size,
            config.intermediate_size,
            module_name=f"{module_prefix}.up_proj" if module_prefix else "")
        self.down_proj = make_linear(
            config,
            config.intermediate_size,
            config.hidden_size,
            module_name=f"{module_prefix}.down_proj" if module_prefix else "")

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        return self.down_proj(
            F.silu(self.gate_proj(hidden_states)) *
            self.up_proj(hidden_states))


# ---------------------------------------------------------------------------
# DecoderLayer  (attention + MLP)
# ---------------------------------------------------------------------------


class DecoderLayer(nn.Module):
    """Single transformer decoder layer.

    Submodule names match checkpoint keys:
        self_attn, mlp, input_layernorm, post_attention_layernorm
    """

    def __init__(self, config: ModelConfig, layer_idx: int) -> None:
        super().__init__()
        self.layer_idx = layer_idx
        self.self_attn = Attention(config, layer_idx=layer_idx)
        self.mlp = MLP(config, layer_idx=layer_idx)
        self.input_layernorm = RMSNorm(config.hidden_size, config.rms_norm_eps)
        self.post_attention_layernorm = RMSNorm(config.hidden_size,
                                                config.rms_norm_eps)

    def forward(
        self,
        hidden_states: torch.Tensor,
        past_key_value: torch.Tensor,
        rope_rotary_cos_sin: torch.Tensor,
        context_lengths: torch.Tensor,
        kvcache_start_index: torch.Tensor,
        attention_mask: "torch.Tensor | None" = None,
        attention_pos_id: "torch.Tensor | None" = None,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        residual = hidden_states
        attn_output, present_key_value = self.self_attn(
            self.input_layernorm(hidden_states),
            past_key_value,
            rope_rotary_cos_sin,
            context_lengths,
            kvcache_start_index,
            attention_mask=attention_mask,
            attention_pos_id=attention_pos_id,
        )
        hidden_states = residual + attn_output

        residual = hidden_states
        hidden_states = residual + self.mlp(
            self.post_attention_layernorm(hidden_states))

        return hidden_states, present_key_value


# ---------------------------------------------------------------------------
# Transformer
# ---------------------------------------------------------------------------


class Transformer(nn.Module):
    """Full attention-only decoder stack.

    Stored as ``model`` inside :class:`CausalLM` so parameter keys
    carry the ``model.`` prefix matching safetensors checkpoint keys.

    Submodules: ``embed_tokens``, ``layers``, ``norm``.

    After ``forward``, the last-layer pre-norm hidden states are also exposed
    on ``self.last_pre_norm_hidden_states`` for subclasses that need to emit
    them as an extra ONNX output (see :class:`CausalLM.emit_hidden_states`).
    """

    def __init__(self, config: ModelConfig) -> None:
        super().__init__()
        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size)
        self.layers = nn.ModuleList([
            DecoderLayer(config, layer_idx=i)
            for i in range(config.num_hidden_layers)
        ])
        self.norm = RMSNorm(config.hidden_size, config.rms_norm_eps)
        # Populated at the end of each forward; see module docstring.
        self.last_pre_norm_hidden_states: "torch.Tensor | None" = None

    def forward(
        self,
        inputs_embeds: torch.Tensor,
        past_key_values: Tuple[torch.Tensor, ...],
        rope_rotary_cos_sin: torch.Tensor,
        context_lengths: torch.Tensor,
        kvcache_start_index: torch.Tensor,
        deepstack_embeds: Tuple[torch.Tensor, ...] = (),
        attention_mask: "torch.Tensor | None" = None,
        attention_pos_id: "torch.Tensor | None" = None,
        output_hidden_states: bool = False,
    ) -> Tuple[torch.Tensor, Tuple, "Tuple | None"]:
        hidden_states = inputs_embeds
        present_key_values_list: List[torch.Tensor] = []
        all_hidden_states: list = []

        for layer_index, layer in enumerate(self.layers):
            if output_hidden_states:
                all_hidden_states.append(hidden_states)

            hidden_states, next_key_value = layer(
                hidden_states,
                past_key_values[layer_index],
                rope_rotary_cos_sin,
                context_lengths,
                kvcache_start_index,
                attention_mask=attention_mask,
                attention_pos_id=attention_pos_id,
            )
            present_key_values_list.append(next_key_value)

            # Multimodal deepstack visual embedding (post-layer, first N layers).
            if layer_index < len(deepstack_embeds):
                hidden_states = hidden_states + deepstack_embeds[layer_index]

        # Expose the last-layer pre-norm residual stream (= final DecoderLayer
        # output) for subclasses that need it as an extra ONNX output.  This
        # matches the HuggingFace ``_can_record_outputs["hidden_states"] =
        # DecoderLayer`` hook point used by Qwen3-Omni Thinker, whose Talker
        # consumes exactly this tensor.
        self.last_pre_norm_hidden_states = hidden_states

        normed = self.norm(hidden_states)

        if output_hidden_states:
            all_hidden_states.append(normed)

        return (normed, tuple(present_key_values_list),
                tuple(all_hidden_states) if output_hidden_states else None)


# ---------------------------------------------------------------------------
# CausalLM
# ---------------------------------------------------------------------------


class CausalLM(nn.Module):
    """Causal LM wrapper: Transformer + lm_head.

    The inner ``Transformer`` is stored as attribute ``model`` so all its
    parameters carry the ``model.`` prefix matching checkpoint key prefixes.

    Subclasses can set the class attribute ``emit_hidden_states = True`` to
    expose the full-sequence last-layer normed ``hidden_states`` as an extra
    ONNX output (needed by Qwen3-Omni for the thinker → talker handoff).
    This is independent of ``config.eagle_base``.
    """

    #: Subclasses override to True when the model must emit ``hidden_states``
    #: as an ONNX output in addition to ``logits``.
    emit_hidden_states: bool = False

    def __init__(self, config: ModelConfig) -> None:
        super().__init__()
        self.config = config

        self.model = Transformer(config)

        self.lm_head = make_linear(config,
                                   config.hidden_size,
                                   config.vocab_size,
                                   bias=False,
                                   module_name="lm_head")

    def tie_weights(self) -> None:
        """Clone embed_tokens.weight into lm_head.weight when tie_word_embeddings=True.

        HuggingFace checkpoints with ``tie_word_embeddings=True`` omit
        ``lm_head.weight`` from the saved file.  We clone (not share) the
        embedding weight so that lm_head and embed_tokens remain independent
        tensors, which is required for correct ONNX export.

        Called by :func:`~loader.load_weights` after checkpoint loading.

        Skipped when lm_head is a quantized module (e.g. FP8Linear in
        MIXED_PRECISION checkpoints) that stores its own weight.
        """
        if not self.config.tie_word_embeddings:
            return
        if not isinstance(self.lm_head, FP16Linear):
            return
        embed_weight = self.model.embed_tokens.weight
        self.lm_head.weight = nn.Parameter(embed_weight.detach().clone(),
                                           requires_grad=False)

    def onnx_export_spec(self) -> OnnxSpec:
        """Return all model-specific parameters needed for ONNX export.

        Builds dummy inputs, I/O name lists, and dynamic shape descriptors
        matching the flat wrapper signature produced by :func:`_make_flat_wrapper`.

        When ``config.eagle_base`` is True, extra inputs (``attention_pos_id``,
        ``attention_mask``) and an extra output (``hidden_states``) are added
        for EAGLE3 base-model tree-attention verification.
        """
        config = self.config
        Na = config.num_hidden_layers
        Nd = config.num_deepstack_features
        eagle_base = config.eagle_base
        device = next(itertools.chain(self.parameters(),
                                      self.buffers())).device
        dtype16 = torch.float16
        batch_size, seq_len, past_len, max_pos = (_BATCH_SIZE, _SEQ_LEN,
                                                  _PAST_LEN, _MAX_POS)

        inputs_embeds = torch.zeros(batch_size,
                                    seq_len,
                                    config.hidden_size,
                                    dtype=dtype16,
                                    device=device)
        kv_dtype = (torch.float8_e4m3fn
                    if config.quant.kv_cache_quant == "fp8" else dtype16)
        past_key_values_list: List[torch.Tensor] = [
            torch.zeros(batch_size,
                        2,
                        config.num_key_value_heads,
                        past_len,
                        config.head_dim,
                        dtype=kv_dtype,
                        device=device) for _ in range(Na)
        ]
        rotary_dim = int(config.head_dim * config.partial_rotary_factor)
        rope_rotary_cos_sin = torch.zeros(batch_size,
                                          max_pos,
                                          rotary_dim,
                                          dtype=torch.float32,
                                          device=device)
        context_lengths = torch.zeros(batch_size,
                                      dtype=torch.int32,
                                      device=device)
        kvcache_start_index = torch.zeros(batch_size,
                                          dtype=torch.int32,
                                          device=device)
        last_token_ids = torch.zeros(batch_size,
                                     1,
                                     dtype=torch.int64,
                                     device=device)

        deepstack_embeds_list: List[torch.Tensor] = [
            torch.zeros(batch_size,
                        seq_len,
                        config.hidden_size,
                        dtype=dtype16,
                        device=device) for _ in range(Nd)
        ]

        args = (inputs_embeds, *past_key_values_list, rope_rotary_cos_sin,
                context_lengths, kvcache_start_index, last_token_ids,
                *deepstack_embeds_list)

        input_names = (["inputs_embeds"] +
                       [f"past_key_values_{i}" for i in range(Na)] + [
                           "rope_rotary_cos_sin", "context_lengths",
                           "kvcache_start_index", "last_token_ids"
                       ] + [f"deepstack_embeds_{i}" for i in range(Nd)])
        output_names = (["logits"] +
                        [f"present_key_values_{i}" for i in range(Na)])
        if self.emit_hidden_states and not eagle_base:
            output_names = (["logits", "hidden_states"] +
                            [f"present_key_values_{i}" for i in range(Na)])

        batch = torch.export.Dim("batch", min=1, max=256)
        seq = torch.export.Dim("seq_len", min=1, max=32768)
        pos = torch.export.Dim("max_pos", min=1, max=32768)
        past = torch.export.Dim("past_len", min=1, max=32768)
        rope_batch = torch.export.Dim("rope_batch", min=1, max=256)
        kv_batch = torch.export.Dim("kv_batch", min=1, max=256)

        num_selected = torch.export.Dim("num_selected", min=1,
                                        max=256) if eagle_base else None
        all_shapes: list = [{0: batch, 1: seq}]  # inputs_embeds
        for _ in range(Na):
            all_shapes.append({0: batch, 3: past})  # past_key_values_i
        all_shapes.append({0: rope_batch, 1: pos})  # rope_rotary_cos_sin
        all_shapes.append({0: batch})  # context_lengths
        all_shapes.append({0: kv_batch})  # kvcache_start_index
        if eagle_base:
            all_shapes.append({0: batch, 1: num_selected})  # last_token_ids
        else:
            all_shapes.append({0: batch})  # last_token_ids
        for _ in range(Nd):
            all_shapes.append({0: batch, 1: seq})  # deepstack_embeds_i

        # EAGLE3 base: add tree-attention inputs and hidden_states output.
        if eagle_base:
            attention_pos_id = torch.zeros(batch_size,
                                           seq_len,
                                           dtype=torch.int32,
                                           device=device)
            attention_mask = torch.zeros(batch_size,
                                         seq_len,
                                         seq_len + past_len,
                                         dtype=torch.int32,
                                         device=device)
            args = args + (attention_pos_id, attention_mask)
            input_names = input_names + ["attention_pos_id", "attention_mask"]
            output_names = ["logits", "hidden_states"
                            ] + [f"present_key_values_{i}" for i in range(Na)]

            # Use separate dims for attention_mask/pos_id so they don't
            # share seq_len with inputs_embeds.  The TRT builder sets
            # different profiles per phase (prefill: attention seq=1,
            # generation: attention seq=maxVerifyTreeSize).  Shared dims
            # would force the prefill constraint (1) onto inputs_embeds.
            eagle_seq = torch.export.Dim("eagle_seq_len", min=1, max=32768)
            mask_kv_len = torch.export.Dim("mask_kv_len", min=1, max=65536)
            all_shapes.append({0: batch, 1: eagle_seq})  # attention_pos_id
            all_shapes.append({
                0: batch,
                1: eagle_seq,
                2: mask_kv_len
            })  # attention_mask

        wrapped = _make_flat_wrapper(
            self,
            Na,
            Nd,
            eagle_base=eagle_base,
            emit_hidden_states=self.emit_hidden_states)
        wrapped.eval()

        return OnnxSpec(wrapped=wrapped,
                        args=args,
                        input_names=input_names,
                        output_names=output_names,
                        dynamic_shapes=all_shapes)

    def forward(
        self,
        inputs_embeds: torch.Tensor,
        past_key_values: Tuple[torch.Tensor, ...],
        rope_rotary_cos_sin: torch.Tensor,
        context_lengths: torch.Tensor,
        kvcache_start_index: torch.Tensor,
        last_token_ids: torch.Tensor,
        deepstack_embeds: Tuple[torch.Tensor, ...] = (),
        attention_mask: "torch.Tensor | None" = None,
        attention_pos_id: "torch.Tensor | None" = None,
    ) -> Tuple:
        eagle_base = self.config.eagle_base
        hidden_states, present_key_values, all_hidden_states = self.model(
            inputs_embeds,
            past_key_values,
            rope_rotary_cos_sin,
            context_lengths,
            kvcache_start_index,
            deepstack_embeds,
            attention_mask=attention_mask,
            attention_pos_id=attention_pos_id,
            output_hidden_states=eagle_base,
        )

        # Select hidden states for specified token positions before lm_head.
        # last_token_ids: [batch, num_tokens] int64 -- indices into the seq dim.
        # Use trt::gather_nd so the ONNX export emits GatherND(batch_dims=1)
        # instead of GatherElements; TRT handles GatherND natively.
        selected_hidden_states = torch.ops.trt.gather_nd(
            hidden_states, last_token_ids)

        logits = self.lm_head(selected_hidden_states).to(torch.float32)

        if eagle_base and all_hidden_states is not None:
            # EAGLE3 base: concatenate hidden states from 3 selected layers.
            # Layer indices: layer 2, middle layer, near-final layer.
            # Output the full-sequence hidden states (NOT gathered) — the C++
            # runtime selects accepted tokens from these after verification.
            n_layers = len(
                all_hidden_states) - 1  # last entry is normed output
            idx = [2, n_layers // 2, n_layers - 4]
            eagle_hidden = torch.cat([
                all_hidden_states[idx[0]],
                all_hidden_states[idx[1]],
                all_hidden_states[idx[2]],
            ],
                                     dim=-1).to(torch.float16)
            return logits, eagle_hidden, present_key_values

        if self.emit_hidden_states:
            # Full-sequence last-layer pre-norm residual, populated by
            # :meth:`Transformer.forward` (see its docstring for the HF
            # hidden_states hook-point alignment).
            return logits, self.model.last_pre_norm_hidden_states, \
                present_key_values

        return logits, present_key_values
